config/routes.rb
Rails.application.routes.draw do
  resources :maps
  resources :unions
  resources :players
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  has_and_belongs_to_many :unions
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :union
end

app/models/union.rb
class Union < ApplicationRecord
  has_many :players
  has_and_belongs_to_many :maps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: %i[ show edit update destroy ]

  # GET /maps or /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1 or /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps or /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: "Map was successfully created." }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1 or /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: "Map was successfully updated." }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1 or /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: "Map was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def map_params
      params.require(:map).permit(:name, :startx, :starty, :endx, :endy, :height, :width, :min_activeness, :max_activeness, :min_prosperity, :max_prosperity)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :x, :y, :prosperity, :activeness, :kills, :status, :union_id, :blueprints, :attention)
    end
end

app/controllers/unions_controller.rb
class UnionsController < ApplicationController
  before_action :set_union, only: %i[ show edit update destroy ]

  # GET /unions or /unions.json
  def index
    @unions = Union.all
  end

  # GET /unions/1 or /unions/1.json
  def show
  end

  # GET /unions/new
  def new
    @union = Union.new
  end

  # GET /unions/1/edit
  def edit
  end

  # POST /unions or /unions.json
  def create
    @union = Union.new(union_params)

    respond_to do |format|
      if @union.save
        format.html { redirect_to @union, notice: "Union was successfully created." }
        format.json { render :show, status: :created, location: @union }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @union.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unions/1 or /unions/1.json
  def update
    respond_to do |format|
      if @union.update(union_params)
        format.html { redirect_to @union, notice: "Union was successfully updated." }
        format.json { render :show, status: :ok, location: @union }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @union.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unions/1 or /unions/1.json
  def destroy
    @union.destroy
    respond_to do |format|
      format.html { redirect_to unions_url, notice: "Union was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_union
      @union = Union.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def union_params
      params.require(:union).permit(:name, :members, :prosperity, :region, :cities, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/unions_helper.rb
module UnionsHelper
end

app/views/application/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ILMap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to :Unions,  unions_path,  class:"nav-link" %>
      <li class="nav-item"><%= link_to :Players, players_path, class:"nav-link" %>
      <li class="nav-item"><%= link_to :Maps,    maps_path,    class:"nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ilmap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">

    <!--%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "menu" %>
    <div class=container>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_with(model: map) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
        <% map.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :startx %>
    <%= form.number_field :startx %>
  </div>

  <div class="field">
    <%= form.label :starty %>
    <%= form.number_field :starty %>
  </div>

  <div class="field">
    <%= form.label :endx %>
    <%= form.number_field :endx %>
  </div>

  <div class="field">
    <%= form.label :endy %>
    <%= form.number_field :endy %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width %>
  </div>

  <div class="field">
    <%= form.label :min_activeness %>
    <%= form.number_field :min_activeness %>
  </div>

  <div class="field">
    <%= form.label :max_activeness %>
    <%= form.number_field :max_activeness %>
  </div>

  <div class="field">
    <%= form.label :min_prosperity %>
    <%= form.number_field :min_prosperity %>
  </div>

  <div class="field">
    <%= form.label :max_prosperity %>
    <%= form.number_field :max_prosperity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<table class=table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Startx</th>
      <th>Starty</th>
      <th>Endx</th>
      <th>Endy</th>
      <th>Height</th>
      <th>Width</th>
      <th>Min activeness</th>
      <th>Max activeness</th>
      <th>Min prosperity</th>
      <th>Max prosperity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= link_to map.name, map %></td>
        <td><%= map.startx %></td>
        <td><%= map.starty %></td>
        <td><%= map.endx %></td>
        <td><%= map.endy %></td>
        <td><%= map.height %></td>
        <td><%= map.width %></td>
        <td><%= map.min_activeness %></td>
        <td><%= map.max_activeness %></td>
        <td><%= map.min_prosperity %></td>
        <td><%= map.max_prosperity %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Startx:</strong>
  <%= @map.startx %>
</p>

<p>
  <strong>Starty:</strong>
  <%= @map.starty %>
</p>

<p>
  <strong>Endx:</strong>
  <%= @map.endx %>
</p>

<p>
  <strong>Endy:</strong>
  <%= @map.endy %>
</p>

<p>
  <strong>Height:</strong>
  <%= @map.height %>
</p>

<p>
  <strong>Width:</strong>
  <%= @map.width %>
</p>

<p>
  <strong>Min activeness:</strong>
  <%= @map.min_activeness %>
</p>

<p>
  <strong>Max activeness:</strong>
  <%= @map.max_activeness %>
</p>

<p>
  <strong>Min prosperity:</strong>
  <%= @map.min_prosperity %>
</p>

<p>
  <strong>Max prosperity:</strong>
  <%= @map.max_prosperity %>
</p>

<p>
  <strong>Unions:</strong>
  <ul>
  <% @map.unions.each do |u| %>
    <li><%= link_to u.name, u %>
  <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

<hr>
<div class="border: solid 1px">
  <canvas id=canvas height=400 width=400></canvas>
</div>

<script>
  const canvas = document.getElementById('canvas');
  const ctx    = canvas.getContext('2d');
  const scale  = 400 / 10000;

  ctx.strokeStyle = 'black';
  //ctx.fill()

  ctx.lineWidth   = 1;
  ctx.beginPath();
  //ctx.rect(0,0,200,200);
  ctx.ellipse(200,200,199,199,0,0,360);
  ctx.stroke();

  ctx.fillStyle = 'black';
  ctx.beginPath();
  ctx.ellipse(200,200,5,5,0,0,360);
  ctx.stroke();

<% puts "hi count=#{Player.all.count}" %>
  <% Player.all.each do |p| %>
    <% puts "#{p.x},#{p.y}" %>
    var r = <%= (p.prosperity + 1000) / 1000 %>;

    ctx.beginPath();
    ctx.ellipse(<%= p.x * 400 / 10000 %>,<%= 400 - p.y * 400 / 10000 %>, r,r,0,0,360);
    ctx.fillStyle = '<%= p.union.color %>';
    ctx.fill();
  <% end %>
</script>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :x %>
    <%= form.number_field :x %>
  </div>

  <div class="field">
    <%= form.label :y %>
    <%= form.number_field :y %>
  </div>

  <div class="field">
    <%= form.label :prosperity %>
    <%= form.number_field :prosperity %>
  </div>

  <div class="field">
    <%= form.label :activeness %>
    <%= form.number_field :activeness %>
  </div>

  <div class="field">
    <%= form.label :kills %>
    <%= form.number_field :kills %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :union %>
    <%= form.collection_select :union_id, Union.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :blueprints %>
    <%= form.text_field :blueprints %>
  </div>

  <div class="field">
    <%= form.label :attention %>
    <%= form.datetime_local_field :attention %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table class=table>
  <thead>
    <tr>
      <th>Name</th>
      <th>X</th>
      <th>Y</th>
      <th>Prosperity</th>
      <th>Activeness</th>
      <th>Kills</th>
      <th>Status</th>
      <th>Union</th>
      <th>Blueprints</th>
      <th>Attention</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.name, player %></td>
        <td><%= player.x %></td>
        <td><%= player.y %></td>
        <td><%= player.prosperity %></td>
        <td><%= player.activeness %></td>
        <td><%= player.kills %></td>
        <td><%= player.status %></td>
        <td><%= player.union.name %></td>
        <td><%= player.blueprints %></td>
        <td><%= player.attention %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>X:</strong>
  <%= @player.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @player.y %>
</p>

<p>
  <strong>Prosperity:</strong>
  <%= @player.prosperity %>
</p>

<p>
  <strong>Activeness:</strong>
  <%= @player.activeness %>
</p>

<p>
  <strong>Kills:</strong>
  <%= @player.kills %>
</p>

<p>
  <strong>Status:</strong>
  <%= @player.status %>
</p>

<p>
  <strong>Union:</strong>
  <%= link_to @player.union.name, @player.union %>
</p>

<p>
  <strong>Blueprints:</strong>
  <%= @player.blueprints %>
</p>

<p>
  <strong>Attention:</strong>
  <%= @player.attention %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/unions/_form.html.erb
<%= form_with(model: union) do |form| %>
  <% if union.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(union.errors.count, "error") %> prohibited this union from being saved:</h2>

      <ul>
        <% union.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :members %>
    <%= form.number_field :members %>
  </div>

  <div class="field">
    <%= form.label :prosperity %>
    <%= form.number_field :prosperity %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.number_field :region %>
  </div>

  <div class="field">
    <%= form.label :cities %>
    <%= form.number_field :cities %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unions/edit.html.erb
<h1>Editing Union</h1>

<%= render 'form', union: @union %>

<%= link_to 'Show', @union %> |
<%= link_to 'Back', unions_path %>

app/views/unions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unions</h1>

<table class=table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Members</th>
      <th>Prosperity</th>
      <th>Region</th>
      <th>Cities</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unions.each do |union| %>
      <tr>
        <td><%= link_to union.name, union %></td>
        <td><%= union.members %></td>
        <td><%= union.prosperity %></td>
        <td><%= union.region %></td>
        <td><%= union.cities %></td>
        <td><%= union.color %></td>
        <td><%= link_to 'Show', union %></td>
        <td><%= link_to 'Edit', edit_union_path(union) %></td>
        <td><%= link_to 'Destroy', union, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Union', new_union_path %>

app/views/unions/new.html.erb
<h1>New Union</h1>

<%= render 'form', union: @union %>

<%= link_to 'Back', unions_path %>

app/views/unions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @union.name %>
</p>

<p>
  <strong>Members:</strong>
  <%= @union.members %> (<%= @union.players.count %>)
</p>

<p>
  <strong>Prosperity:</strong>
  <%= @union.prosperity %> (<%= @union.players.sum {|p| p.prosperity } %>)
</p>

<p>
  <strong>Region:</strong>
  <%= @union.region %>
</p>

<p>
  <strong>Color:</strong>
  <%= @union.color %>
</p>

<p>
  <strong>Cities:</strong>
  <%= @union.cities %>
</p>

<%= link_to 'Edit', edit_union_path(@union) %> |
<%= link_to 'Back', unions_path %>